# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Simula Summer School in Computational Physiology
author: JÃ¸rgen S. Dokken
logo: logo.png

# Cache execution of notebooks

# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  timeout: 1800

# Information about where the book exists on the web
repository:
  url: https://github.com/Simula-SSCP/SSCP_2023_lectures  # Online location of your book
  path_to_book: .  # Optional path to your book, relative to the repository root
  branch: main # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org"

html:
  use_issues_button: true
  use_repository_button: true

  extra_footer: |
    <div>
        This webpage is distributed under the terms of the <a href=https://choosealicense.com/licenses/mit/>MIT License</a>.
        If you use this work, please cite it appropriately.
    </div

parse:
  myst_enable_extensions:
    - "amsmath"
    - "colon_fence"
    - "deflist"
    - "dollarmath"
    - "html_admonition"
    - "html_image"
    - "linkify"
    - "replacements"
    - "smartquotes"
    - "substitution"

sphinx:
  config:
    html_last_updated_fmt: "%b %d, %Y"
    suppress_warnings: ["mystnb.unknown_mime_type"]

exclude_patterns: [README.md]
only_build_toc_files: true
