name: Build lecture webpage

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: ["main"]

env:
  DEB_PYTHON_INSTALL_LAYOUT: deb_system
  IPP_NONINTERACTIVE: "1"

defaults:
  run:
    shell: bash -el {0}

jobs:
  build-book:
    runs-on: ubuntu-latest
    container: ubuntu:22.04

    steps:

      - uses: actions/checkout@v3

      - name: Initialize SSCP conda environment
        uses: ./.github/actions/initialize_conda_env

      - name: Cache executed notebooks
        uses: actions/cache@v3
        with:
          path: _build/.jupyter_cache
          key: jupyter-cache-${{ hashFiles('environment.yml') }}

      - name: Run the lecture notes and build webpage
        run:
          jupyter-book build . -W

      - uses: actions/upload-artifact@v3
        # always upload artifact, which can include error messages
        if: always()
        with:
          name: documentation
          path: ./_build/html
          retention-days: 2
          if-no-files-found: error

      - name: Show error reports
        if: failure()
        run: |
          find _build/html/reports -type f -print -exec cat {} \;
